### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by MrFuFuFu** [forJrking/FontZip#4]
``` java
java -jar sfnttool.jar -s 'xyz' a.ttf mrfu.ttf
Exception in thread "main" java.lang.NullPointerException
    at com.google.typography.font.tools.sfnttool.GlyphCoverage.getGlyph(Unknown Source)
    at com.google.typography.font.tools.sfnttool.GlyphCoverage.touchGlyph(Unknown Source)
    at com.google.typography.font.tools.sfnttool.GlyphCoverage.getGlyphCoverage(Unknown Source)
    at com.google.typography.font.tools.sfnttool.SfntTool.subsetFontFile(Unknown Source)
    at com.google.typography.font.tools.sfnttool.SfntTool.main(Unknown Source)
```

**Comment by MrFuFuFu** [comment]
sorry，换了个字体库可以了
